### ISSUE TITLE
Shaman et al estimation

### ISSUE THREAD

**Issue by aakhmetz** [caijun/humidity#6]
Regarding a different value for the estimate in [humidity/vignettes/ivs-sh.html](https://cran.r-project.org/web/packages/humidity/vignettes/ivs-sh.html), I think there could be two explanations:
1) the final choice of q=-180.0 in Shaman et al was also guided by the fit to ILI data
2) Shaman et al actually fitted to another source of Lowen et al. 2017 and Lowen et al 2018 (Figure 1A in Shaman et al PlosCompBio), not to Harper 1961 (Figure 1B). Harper 1961 provides virus survival ability, whereas Lowen et al. virus transmissibility.

Regards,
Andrei

**Comment by caijun** [comment]
Thank you for your explanations. I have collated the data on transmission experiments from Lowen et al. 2007, 2008 and updated the vignette by adding the log-linear regression of guinea pig airborne influenza virus transmission data on specific humidity.  You can view the latest vignette by installing **humidity** via github.

```
devtools::install_github("caijun/humidity", ref = "cebdca9", build_vignettes = TRUE)
```


The following are the results.

```
# load humidity package
library(humidity)

# display built-in guinea pig airborne influenza virus transmission data
head(ivt)

##    T RH  PT          source
## 1 20 20 100 Lowen.etal-2007
## 2 20 20  75 Lowen.etal-2007
## 3 20 35 100 Lowen.etal-2007
## 4 20 35 100 Lowen.etal-2007
## 5 20 50  25 Lowen.etal-2007
## 6 20 50  25 Lowen.etal-2007

library(tidyverse)
ivt <- ivt %>% 
  mutate(Tk = C2K(T), # tempature in Kelvin
         Es = SVP(Tk), # saturation vapor pressure in hPa
         E = WVP2(RH, Es), # partial water vapor pressure in Pa
         rho = AH(E, Tk), # absolute humidity in kg/m^3
         q = SH(E), # specific humidity in kg/kg
         omega = MR(q), # mixing ratio in kg/kg
         ) %>%
  mutate(PT = ifelse(PT == 0, 1, PT)) # add a small quantity to avoid taking log of zero
# check the calculation results
head(ivt)

##    T RH  PT          source     Tk       Es         E         rho
## 1 20 20 100 Lowen.etal-2007 293.15 23.63899  472.7798 0.003494447
## 2 20 20  75 Lowen.etal-2007 293.15 23.63899  472.7798 0.003494447
## 3 20 35 100 Lowen.etal-2007 293.15 23.63899  827.3646 0.006115282
## 4 20 35 100 Lowen.etal-2007 293.15 23.63899  827.3646 0.006115282
## 5 20 50  25 Lowen.etal-2007 293.15 23.63899 1181.9494 0.008736118
## 6 20 50  25 Lowen.etal-2007 293.15 23.63899 1181.9494 0.008736118
##             q       omega
## 1 0.002907371 0.002915848
## 2 0.002907371 0.002915848
## 3 0.005094650 0.005120738
## 4 0.005094650 0.005120738
## 5 0.007287741 0.007341242
## 6 0.007287741 0.007341242
```
The zero transmission efficiencies have a significant influence on the coefficient estimate of SH. Therefore, instead of a linear regression model with the log transformed response variable, a GLM model with Gaussian family and log link is used to obtain a robust coefficient estimate.

```
# log-linear regression of influenza virus airborne  transmission on specific humididty
loglm <- glm(PT ~ q, family = gaussian(link = "log"), data = ivt)
summary(loglm)

## 
## Call:
## glm(formula = PT ~ q, family = gaussian(link = "log"), data = ivt)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -49.906  -14.616   -9.527    5.985   51.440  
## 
## Coefficients:
##              Estimate Std. Error t value Pr(>|t|)    
## (Intercept)    4.9291     0.2077  23.733  < 2e-16 ***
## q           -186.5339    52.7765  -3.534  0.00186 ** 
## ---
## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
## 
## (Dispersion parameter for gaussian family taken to be 726.2067)
## 
##     Null deviance: 37884  on 23  degrees of freedom
## Residual deviance: 15977  on 22  degrees of freedom
## AIC: 230.13
## 
## Number of Fisher Scoring iterations: 6
```

The regression coefficient of SH q is significant with a p-value equal to 0.0019, which is the same as that annotated in Fig. 1 (F) of Shaman and Kohn (2009). Furthermore, the coefficient estimate for SH q is -187, which is very close to the value of a=−180 that was finally used in the functional relationship between R0(t) and q(t) per Equation 4 in Shaman et al. (2010). These verified the correctness of various AH measures calculated by **humidity** package.

I think your second explanation is on the point. Thank you again.

**Comment by aakhmetz** [comment]
@caijun san, thank you very much for your quick response!

That time I have also tried by stan and it gave something similar
```r
fit_glm = rstanarm::stan_glm(fraction ~ SH, family = gaussian(link = "log"), data = dfLowen, algorithm = "sampling")
summary(fit_glm,digits=2)
```
which resulted:
```r
Model Info:
 function:     stan_glm
 family:       gaussian [log]
 formula:      fraction ~ SH
 algorithm:    sampling
 sample:       4000 (posterior sample size)
 priors:       see help('prior_summary')
 observations: 24
 predictors:   2

Estimates:
              mean    sd      10%     50%     90%  
(Intercept)    0.32    0.22    0.04    0.32    0.59
SH          -196.52   56.76 -269.01 -190.44 -130.10
sigma          0.28    0.04    0.23    0.28    0.34

Fit Diagnostics:
           mean   sd   10%   50%   90%
mean_PPD 0.48   0.08 0.37  0.48  0.58 

The mean_ppd is the sample average posterior predictive distribution of the outcome variable (for details see help('summary.stanreg')).

MCMC diagnostics
              mcse Rhat n_eff
(Intercept)   0.01 1.00 1636 
SH            1.80 1.00  995 
sigma         0.00 1.00 1631 
mean_PPD      0.00 1.00 2388 
log-posterior 0.04 1.00 1063 

For each parameter, mcse is Monte Carlo standard error, n_eff is a crude measure of effective sample size, and Rhat is the potential scale reduction factor on split chains (at convergence Rhat=1).
```

I have also tried to write my own stan program, but I obtained a more distant estimate of ca. -220. Maybe I will ask about that later at the discourse-website of stan. But it is definitely less related to the this issue. 

What I saw from the fit thought that indeed whether it is 180.0 or 220.0, it does give something comparable:
![index](https://user-images.githubusercontent.com/2173206/70539098-83eba100-1ba6-11ea-9dfe-3c3acb475714.png)
